kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: px-mongo-pvc1
   annotations:
     volume.beta.kubernetes.io/storage-class: px-ha-sc1
spec:
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi