apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: worker
    name: redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis
    app: worker
